### PR TITLE
Pami

### PR DESCRIPTION
**Pull request by paminus-kingori**
Redesigned the sign up and login page

### CODE REVIEW

**Comment by PaymasterMax** [comment]
The error message is not visible that much. can you check on it? (The login page)
image
Hey paminus i got a little problem with forgot password page.
image

**Comment by PaymasterMax** [comment]
Pam, and dont forget about .gitignore the file .vscode is uploaded onto github, you dont wanna do that. here is the screenshot of the file to add to git ignore
image

**Comment by paminus-kingori** [comment]
> The error message is not visible that much. can you check on it? (The login page)
> image
> Hey paminus i got a little problem with forgot password page.
> image

will look into that

**Comment by paminus-kingori** [comment]
the label,,must be an z-index thing, will cover that too

**Pull request merged**
